language: node_js
node_js:
  - "node"
cache:
  yarn: true
install:
  - yarn install
before_script:
  - curl -L
    https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
    > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - yarn test
  - yarn lint
after_script:
  - codecov -f coverage/*.json
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
deploy:
  provider: script
  on:
    branch: production
  skip_cleanup: true
  script:
    - npx semantic-release
