notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4b811010ea4b8f931e2c
    on_success: change # options: [always|never|change] default: always
    on_failure: always # options: [always|never|change] default: always
    on_start: never # options: [always|never|change] default: always
